// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjw9sGHqc_wTwV97oWmLEPAG2vlevr4EE',
    appId: '1:522285508016:web:b4435719c37b2a290fe275',
    messagingSenderId: '522285508016',
    projectId: 'mela-skin',
    authDomain: 'mela-skin.firebaseapp.com',
    storageBucket: 'mela-skin.firebasestorage.app',
    measurementId: 'G-1HGRVG0KB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7dF3VEvZLGeLw4qG4_9eczzFB_PTIJMQ',
    appId: '1:522285508016:android:aa7cfc11af1139550fe275',
    messagingSenderId: '522285508016',
    projectId: 'mela-skin',
    storageBucket: 'mela-skin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBahmJDdK7ojxigJ9nlZGqoHFbufsQ7yZc',
    appId: '1:522285508016:ios:e9c3ce5ec653a82d0fe275',
    messagingSenderId: '522285508016',
    projectId: 'mela-skin',
    storageBucket: 'mela-skin.firebasestorage.app',
    iosBundleId: 'com.heda.melaSkinPatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBahmJDdK7ojxigJ9nlZGqoHFbufsQ7yZc',
    appId: '1:522285508016:ios:e9c3ce5ec653a82d0fe275',
    messagingSenderId: '522285508016',
    projectId: 'mela-skin',
    storageBucket: 'mela-skin.firebasestorage.app',
    iosBundleId: 'com.heda.melaSkinPatient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjw9sGHqc_wTwV97oWmLEPAG2vlevr4EE',
    appId: '1:522285508016:web:ee9010d36d7fc9bc0fe275',
    messagingSenderId: '522285508016',
    projectId: 'mela-skin',
    authDomain: 'mela-skin.firebaseapp.com',
    storageBucket: 'mela-skin.firebasestorage.app',
    measurementId: 'G-62SYPKG5G3',
  );
}
